version: '3.7'
services:

  mysql:
    image: artifactory.digikala.com/docker/mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tehran
    networks:
        - backend
  redis:
    image: redis:latest  # Pull the latest Redis image
    container_name: redis-server  # Name the container
    ports:
      - "6379:6379"  # Expose Redis on the default port (6379)
    volumes:
      - redis-data:/data  # Persistent volume for Redis data
    restart: always
    networks:
        - backend
  api:
    build: .
    container_name: pairfect_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mysql
    env_file:
      - .env.docker
    networks:
      - backend
    expose:
      - "8000:8000"
    command:
      - poetry run uvicorn main:app
  celery_worker:
    build: .
    container_name: pairfect_celery_worker
    restart: always
    depends_on:
      - redis
      - mysql
    command: poetry run celery -A main:scheduler worker --loglevel=info
    env_file:
      - .env.docker
    networks:
      - backend
  celery_beat:
    build: .
    container_name: pairfect_celery_beat
    restart: always
    depends_on:
      - redis
      - mysql
    command: poetry run celery -A main:scheduler beat --loglevel=info
    env_file:
      - .env.docker
    networks:
      - backend



networks:
#  elk:
#    driver: bridge
  backend:
    driver: bridge

volumes:
#    elastic_data: {}
    mysql_data: {}
    mysql_logs: {}
    redis-data: {}


