[tool.poetry]
name = "pindo-productmatching"
version = "0.1.0"
description = ""
authors = ["AmirHossein Advari <amiradvari@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
datasketch = "^1.6.5"
sqlalchemy = "^2.0.37"
alembic = "^1.14.1"
pyyaml = "^6.0.2"
celery = "^5.4.0"
eventlet = "^0.39.0"
pymysql = "^1.1.1"
sqlalchemy-celery-beat = "^0.8.0"
python-dotenv = "^1.0.1"
colorlog = "^6.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
